import:
  - source: QubesOS/qubes-continuous-integration:R4.1/travis-base-r4.1.yml
    mode: deep_merge
  - source: QubesOS/qubes-continuous-integration:R4.1/travis-dom0-r4.1.yml
  - source: QubesOS/qubes-continuous-integration:R4.1/travis-vms-r4.1.yml
language: python
python:
  - '3.6'
install:
 - pip install --quiet -r ci/requirements.txt
 - git clone https://github.com/QubesOS/qubes-builder ~/qubes-builder
 - git clone https://github.com/QubesOS/qubes-core-admin-client ~/core-admin-client
script:
 - PYTHONPATH=~/core-admin-client python3 -m pylint --rcfile=.pylintrc qui
 - ~/qubes-builder/scripts/travis-build

